modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "durability"
version = "${version}"
displayName = "Durability"
authors = "Hans"
description = '''
Allows global increasing or decreasing of tool, armor, and weapon durability.
'''
#logoFile = ""

[[dependencies.durability]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.durability]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.durability]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "durability.mixins.json"
